apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: AWS_ECR_URI
        ports:
          - containerPort: 8080
        imagePullPolicy: Always      
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
